name: CI/CD with Gradle

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "correto"
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          chmod +x ./docker-build.sh
          ./docker-build.sh
    # dockerfile을 통해 이미지를 빌드하고, 이를 docker repo로 push 합니다.
    # 이 때 사용되는 ${{ secrets.DOCKER_REPO }}/directors-dev 가 위에서 만든 도커 repository 입니다.
      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build . -t ${{ secrets.DOCKERHUB_REPO }}/restaurant-api:develop
          docker push ${{ secrets.DOCKER_REPO }}/restaurant-api:develop
